theme: minima
title: My information
author: davidhannnn
email: dhan@ebnet.org
description: >
 This will contain my name, social media information,
 brag sheet and a picture of me.



show_excerpts: true 
